// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.

// https://developers.google.com/web/fundamentals/primers/service-workers/?hl=ja
const CACHE_NAME = 'my-site-cache-v1';
const urlsToCache = [
    '/',
    '/styles/main.css',
    '/scripts/main.js'
];

self.addEventListener ('install', (event) => {
    event.waitUntil (
        caches.open (CACHE_NAME)
            .then ((cache) => {
                console.log ('Opened cache');
                return cache.addAll (urlsToCache);
            })
    );
});